MVC-Eterna/Models/Category.cs
namespace MVC_Eterna.Models
{
    public class Category
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public List<Project> Projects { get; set; }
    }
}

MVC-Eterna/Models/Feature.cs
namespace MVC_Eterna.Models
{
    public class Feature
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Desc { get; set; }
        public string Icon { get; set; }
    }
}

MVC-Eterna/Models/Member.cs
namespace MVC_Eterna.Models
{
    public class Member
    {
        public int Id { get; set; }
        public string Name { get; set; } 
        public string Occupation { get; set; }
        public string Description { get; set; }
        public string Image {  get; set; }  
        public List<SocialMedia> SocialMedia { get; set; }  
    }
}

MVC-Eterna/Models/Project.cs
namespace MVC_Eterna.Models
{
    public class Project
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public int CategoryId { get; set; }
        public string URL { get; set; }
        public DateTime Date { get; set; }
        public Category Category { get; set; }
        public List<ProjectImg> ProjectImgs { get; set; }
    }
}

MVC-Eterna/Models/ProjectImg.cs
namespace MVC_Eterna.Models
{
    public class ProjectImg
    {
        public int Id { get; set; }
        public int ProjectId { get; set; }
        public string Name { get; set; }
        public bool IsPrimary { get; set; }
        public Project Project { get; set; }
    }
}

MVC-Eterna/Models/Service.cs
namespace MVC_Eterna.Models
{
    public class Service
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Desc { get; set; }
        public string Icon { get; set; }
    }
}

MVC-Eterna/Models/SliderItem.cs
namespace MVC_Eterna.Models
{
    public class SliderItem
    {
        public int Id { get; set; }
        public string Title1 { get; set; }
        public string Title2 { get; set; }
        public string Image { get; set; }
        public string Desc { get; set; }
        public string ButtonContent { get; set; }
        public int Order { get; set; }
    }
}

MVC-Eterna/Models/SocialMedia.cs
namespace MVC_Eterna.Models
{
    public class SocialMedia
    {
        public int Id { get; set; } 
        public string Name { get; set; }
        public string Icon { get; set; }
        public Member Member { get; set; }
    }
}

MVC-Eterna/ViewModels/HomeViewModel.cs
using MVC_Eterna.Models;

namespace MVC_Eterna.ViewModels
{
    public class HomeViewModel
    {
        public List<Feature> Features { get; set; }     
        public List<Service> Services { get; set; }
        public List<SliderItem> Sliders { get; set; }

    }
}

MVC-Eterna/ViewModels/PortfolioDetailsViewModel.cs
using MVC_Eterna.Models;

namespace MVC_Eterna.ViewModels
{
    public class PortfolioDetailsViewModel
    {
        public Project Project { get; set; }
        public List<ProjectImg> ProjectImgs { get; set; }
    }
}

MVC-Eterna/ViewModels/PortfolioViewModel.cs
using MVC_Eterna.Models;

namespace MVC_Eterna.ViewModels
{
    public class PortfolioViewModel
    {
        public List<Project> Projects { get; set; }
        public List<Category> Categories { get; set; }
        
    }
}

MVC-Eterna/ViewModels/TeamViewModel.cs
using MVC_Eterna.Models;

namespace MVC_Eterna.ViewModels
{
    public class TeamViewModel
    {
        public List<Member> Members { get; set; }
    }
}

MVC-Eterna/Controllers/AboutController.cs
using Microsoft.AspNetCore.Mvc;
using MVC_Eterna.Models;
using System.Diagnostics;
namespace MVC_Eterna.Controllers;


public class AboutController:Controller
{
    public IActionResult Index()
    {
        return View();
    }
}

MVC-Eterna/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using MVC_Eterna.Data;
using MVC_Eterna.Models;
using MVC_Eterna.ViewModels;
using System.Diagnostics;

namespace MVC_Eterna.Controllers
{
    public class HomeController : Controller
    {
        private AppDbContext _context;

        public HomeController(AppDbContext context)
        {
            _context = context;
                
        }
        public IActionResult Index()
        {
            HomeViewModel vm = new HomeViewModel()
            {
                Features = _context.Features.ToList(),
                Services = _context.Services.ToList(),
                Sliders = _context.SliderItems.OrderByDescending(x=> x.Order).ToList()    
            };
            return View(vm);
        }

       
    }
}

MVC-Eterna/Controllers/PortfolioController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.Build.Evaluation;
using Microsoft.EntityFrameworkCore;
using MVC_Eterna.Data;
using MVC_Eterna.ViewModels;

namespace MVC_Eterna.Controllers
{
    public class PortfolioController:Controller
    {
        public AppDbContext _context;
        public PortfolioController(AppDbContext context)
        {
            _context = context; 
        }
        public IActionResult Index()
        {
            PortfolioViewModel pvm = new PortfolioViewModel()
            {
                Projects = _context.Projects.Include(x => x.Category).Include(x => x.ProjectImgs).ToList(),  
                Categories = _context.Categories.ToList(),  
            };
            return View(pvm);
        }

        public ActionResult Details(int id)
        {
            var project = _context.Projects.Include(x => x.Category).Include(x => x.ProjectImgs).FirstOrDefault(p => p.Id == id);

            PortfolioDetailsViewModel vm = new PortfolioDetailsViewModel()
            {
                Project = project,
                ProjectImgs = project.ProjectImgs.ToList()
            };

            return View(vm);
        }

    }
}

MVC-Eterna/Controllers/ServicesController.cs
using Microsoft.AspNetCore.Mvc;
using MVC_Eterna.Data;
using MVC_Eterna.Models;

namespace MVC_Eterna.Controllers
{
    public class ServicesController : Controller
    {
        private AppDbContext _context;

        public ServicesController(AppDbContext context)
        {
            _context = context;
        }
        public IActionResult Index()
        {
            return View(_context.Services.ToList());
        }
    }
}

MVC-Eterna/Controllers/TeamController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using MVC_Eterna.Data;
using MVC_Eterna.Models;
using MVC_Eterna.ViewModels;
using System.Diagnostics;
namespace MVC_Eterna.Controllers


{
    public class TeamController:Controller
    {
        private AppDbContext _context;

        public TeamController(AppDbContext context)
        {
            _context = context;
        }


        public IActionResult Index()
        {
            TeamViewModel tvm = new TeamViewModel()
            {
                Members = _context.Members.Include(x=> x.SocialMedia).ToList()
            };
            return View(tvm);


        }
    }
}

MVC-Eterna/Views/Home/Index.cshtml
@model HomeViewModel

 <!-- ======= Hero Section ======= -->
  <section id="hero">
    <div class="hero-container">
      <div id="heroCarousel" data-bs-interval="5000" class="carousel slide carousel-fade" data-bs-ride="carousel">

        <ol class="carousel-indicators" id="hero-carousel-indicators"></ol>

        <div class="carousel-inner" role="listbox">


            @foreach (SliderItem item in Model.Sliders)
                {
                    <div class="carousel-item active" style="background-image: url(assets/img/slide/@item.Image)">
                        <div class="carousel-container">
                            <div class="carousel-content">
                                <h2 class="animate__animated animate__fadeInDown">@item.Title1 <span>@item.Title2</span></h2>
                                <p class="animate__animated animate__fadeInUp">@item.Desc</p>
                                <a href="" class="btn-get-started animate__animated animate__fadeInUp">@item.ButtonContent</a>
                            </div>
                        </div>
                    </div>
                }

          @* <!-- Slide 1 -->
          <div class="carousel-item active" style="background-image: url(assets/img/slide/slide-1.jpg)">
            <div class="carousel-container">
              <div class="carousel-content">
                <h2 class="animate__animated animate__fadeInDown">Welcome to <span>Eterna</span></h2>
                <p class="animate__animated animate__fadeInUp">Ut velit est quam dolor ad a aliquid qui aliquid. Sequi ea ut et est quaerat sequi nihil ut aliquam. Occaecati alias dolorem mollitia ut. Similique ea voluptatem. Esse doloremque accusamus repellendus deleniti vel. Minus et tempore modi architecto.</p>
                <a href="" class="btn-get-started animate__animated animate__fadeInUp">Read More</a>
              </div>
            </div>
          </div>

          <!-- Slide 2 -->
          <div class="carousel-item" style="background-image: url(assets/img/slide/slide-2.jpg)">
            <div class="carousel-container">
              <div class="carousel-content">
                <h2 class="animate__animated fanimate__adeInDown">Lorem <span>Ipsum Dolor</span></h2>
                <p class="animate__animated animate__fadeInUp">Ut velit est quam dolor ad a aliquid qui aliquid. Sequi ea ut et est quaerat sequi nihil ut aliquam. Occaecati alias dolorem mollitia ut. Similique ea voluptatem. Esse doloremque accusamus repellendus deleniti vel. Minus et tempore modi architecto.</p>
                <a href="" class="btn-get-started animate__animated animate__fadeInUp">Read More</a>
              </div>
            </div>
          </div>

          <!-- Slide 3 -->
          <div class="carousel-item" style="background-image: url(assets/img/slide/slide-3.jpg)">
            <div class="carousel-container">
              <div class="carousel-content">
                <h2 class="animate__animated animate__fadeInDown">Sequi ea <span>Dime Lara</span></h2>
                <p class="animate__animated animate__fadeInUp">Ut velit est quam dolor ad a aliquid qui aliquid. Sequi ea ut et est quaerat sequi nihil ut aliquam. Occaecati alias dolorem mollitia ut. Similique ea voluptatem. Esse doloremque accusamus repellendus deleniti vel. Minus et tempore modi architecto.</p>
                <a href="" class="btn-get-started animate__animated animate__fadeInUp">Read More</a>
              </div>
            </div>
          </div> *@

        </div>

        <a class="carousel-control-prev" href="#heroCarousel" role="button" data-bs-slide="prev">
          <span class="carousel-control-prev-icon bi bi-chevron-left" aria-hidden="true"></span>
        </a>

        <a class="carousel-control-next" href="#heroCarousel" role="button" data-bs-slide="next">
          <span class="carousel-control-next-icon bi bi-chevron-right" aria-hidden="true"></span>
        </a>

      </div>
    </div>
  </section><!-- End Hero -->

  <main id="main">

    <!-- ======= Featured Section ======= -->
    <section id="featured" class="featured">
      <div class="container">

        <div class="row">
          @foreach (Feature item in Model.Features)
                {
                    <div class="col-lg-4 @(item.Id!=Model.Features[0].Id?"mt-4 mt-lg-0":"")">
                        <div class="icon-box">
                            <i class="@item.Icon"></i>
                            <h3><a href="">@item.Name</a></h3>
                            <p>@item.Desc</p>
                        </div>
                    </div>
                }
        </div>

      </div>
    </section><!-- End Featured Section -->

    <!-- ======= About Section ======= -->
    <section id="about" class="about">
      <div class="container">

        <div class="row">
          <div class="col-lg-6">
            <img src="assets/img/about.jpg" class="img-fluid" alt="">
          </div>
          <div class="col-lg-6 pt-4 pt-lg-0 content">
            <h3>Voluptatem dignissimos provident quasi corporis voluptates sit assumenda.</h3>
            <p class="fst-italic">
              Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore
              magna aliqua.
            </p>
            <ul>
              <li><i class="bi bi-check-circle"></i> Ullamco laboris nisi ut aliquip ex ea commodo consequat.</li>
              <li><i class="bi bi-check-circle"></i> Duis aute irure dolor in reprehenderit in voluptate velit.</li>
              <li><i class="bi bi-check-circle"></i> Ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate trideta storacalaperda mastiro dolore eu fugiat nulla pariatur.</li>
            </ul>
            <p>
              Ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate
              velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in
              culpa qui officia deserunt mollit anim id est laborum
            </p>
          </div>
        </div>

      </div>
    </section><!-- End About Section -->

    <!-- ======= Services Section ======= -->
    <section id="services" class="services">
      <div class="container">

        <div class="row">

            @for (int i = 0; i < Model.Services.Count; i++)
                {
                    <div class="col-lg-4 col-md-6 d-flex align-items-stretch @(i != 0 ? "mt-4 mt-lg-0" : "")">
                    <div class="icon-box">
                        <div class="icon"><i class="@Model.Services[i].Icon"></i></div>
                            <h4><a href="">@Model.Services[i].Name</a></h4>
                            <p>@Model.Services[i].Desc</p>
                    </div>
                </div>
                }

        </div>

      </div>
    </section><!-- End Services Section -->

    <!-- ======= Clients Section ======= -->
    <section id="clients" class="clients">
      <div class="container">

        <div class="section-title">
          <h2>Clients</h2>
          <p>Magnam dolores commodi suscipit. Necessitatibus eius consequatur ex aliquid fuga eum quidem. Sit sint consectetur velit. Quisquam quos quisquam cupiditate. Et nemo qui impedit suscipit alias ea. Quia fugiat sit in iste officiis commodi quidem hic quas.</p>
        </div>

        <div class="clients-slider swiper">
          <div class="swiper-wrapper align-items-center">
            <div class="swiper-slide"><img src="assets/img/clients/client-1.png" class="img-fluid" alt=""></div>
            <div class="swiper-slide"><img src="assets/img/clients/client-2.png" class="img-fluid" alt=""></div>
            <div class="swiper-slide"><img src="assets/img/clients/client-3.png" class="img-fluid" alt=""></div>
            <div class="swiper-slide"><img src="assets/img/clients/client-4.png" class="img-fluid" alt=""></div>
            <div class="swiper-slide"><img src="assets/img/clients/client-5.png" class="img-fluid" alt=""></div>
            <div class="swiper-slide"><img src="assets/img/clients/client-6.png" class="img-fluid" alt=""></div>
            <div class="swiper-slide"><img src="assets/img/clients/client-7.png" class="img-fluid" alt=""></div>
            <div class="swiper-slide"><img src="assets/img/clients/client-8.png" class="img-fluid" alt=""></div>
          </div>
          <div class="swiper-pagination"></div>
        </div>

      </div>
    </section><!-- End Clients Section -->

  </main><!-- End #main -->

MVC-Eterna/Views/Portfolio/Index.cshtml
@model PortfolioViewModel
@{
    ViewData["Title"] = "Index";
}
<main id="main">

    <!-- ======= Breadcrumbs ======= -->
    <section id="breadcrumbs" class="breadcrumbs">
        <div class="container">

            <ol>
                <li><a href="index.html">Home</a></li>
                <li>Portfolio</li>
            </ol>
            <h2>Portfolio</h2>

        </div>
    </section><!-- End Breadcrumbs -->
    <!-- ======= Portfolio Section ======= -->
    <section id="portfolio" class="portfolio">
        <div class="container">

            <div class="row">
                <div class="col-lg-12 d-flex justify-content-center">
                    <ul id="portfolio-flters">
                        <li data-filter="*" class="filter-active">All</li>
                        @foreach (var item in Model.Categories)
                        {
                            <li data-filter=".filter-@item.Id">@item.Name</li>
                        }
                    </ul>
                </div>
            </div>

            <div class="row portfolio-container">

                @foreach (Project item in Model.Projects)
                {
                    <div class="col-lg-4 col-md-6 portfolio-item filter-@item.CategoryId">
                        <div class="portfolio-wrap">
                            <img src="~/assets/img/portfolio/@item.ProjectImgs.OrderBy(x => x.IsPrimary ? 0 : 1).First().Name" class="img-fluid" alt="">
                            <div class="portfolio-info">
                                <h4>@item.Name</h4>
                                <p>@item.Category.Name</p>
                                <div class="portfolio-links">
                                    <a href="~/assets/img/portfolio/@item.ProjectImgs.First().Name" data-gallery="portfolioGallery" class="portfolio-lightbox" title="App 1"><i class="bx bx-plus"></i></a>
                                    <a href="@Url.Action("Details", "Portfolio", new { id = item.Id })" title="More Details"><i class="bx bx-link"></i></a>

                                </div>
                            </div>
                        </div>
                    </div>
                }

            </div>

        </div>
    </section><!-- End Portfolio Section -->
    <!-- ======= Clients Section ======= -->
    <section id="clients" class="clients">
        <div class="container">

            <div class="section-title">
                <h2>Clients</h2>
                <p>Magnam dolores commodi suscipit. Necessitatibus eius consequatur ex aliquid fuga eum quidem. Sit sint consectetur velit. Quisquam quos quisquam cupiditate. Et nemo qui impedit suscipit alias ea. Quia fugiat sit in iste officiis commodi quidem hic quas.</p>
            </div>

            <div class="clients-slider swiper">
                <div class="swiper-wrapper align-items-center">
                    <div class="swiper-slide"><img src="~/assets/img/clients/client-1.png" class="img-fluid" alt=""></div>
                    <div class="swiper-slide"><img src="~/assets/img/clients/client-2.png" class="img-fluid" alt=""></div>
                    <div class="swiper-slide"><img src="~/assets/img/clients/client-3.png" class="img-fluid" alt=""></div>
                    <div class="swiper-slide"><img src="~/assets/img/clients/client-4.png" class="img-fluid" alt=""></div>
                    <div class="swiper-slide"><img src="~/assets/img/clients/client-5.png" class="img-fluid" alt=""></div>
                    <div class="swiper-slide"><img src="~/assets/img/clients/client-6.png" class="img-fluid" alt=""></div>
                    <div class="swiper-slide"><img src="~/assets/img/clients/client-7.png" class="img-fluid" alt=""></div>
                    <div class="swiper-slide"><img src="~/assets/img/clients/client-8.png" class="img-fluid" alt=""></div>
                </div>
                <div class="swiper-pagination"></div>
            </div>

        </div>
    </section><!-- End Clients Section -->

</main><!-- End #main -->

MVC-Eterna/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta content="width=device-width, initial-scale=1.0" name="viewport">

    <title>Eterna Bootstrap Template - Index</title>
    <meta content="" name="description">
    <meta content="" name="keywords">

    <!-- Favicons -->
    <link href="~/assets/img/favicon.png" rel="icon">
    <link href="~/assets/img/apple-touch-icon.png" rel="apple-touch-icon">

    <!-- Google Fonts -->
    <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i|Raleway:300,300i,400,400i,500,500i,600,600i,700,700i|Poppins:300,300i,400,400i,500,500i,600,600i,700,700i" rel="stylesheet">

    <!-- Vendor CSS Files -->
    <link href="~/assets/vendor/animate.css/animate.min.css" rel="stylesheet">
    <link href="~/assets/vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet">
    <link href="~/assets/vendor/bootstrap-icons/bootstrap-icons.css" rel="stylesheet">
    <link href="~/assets/vendor/boxicons/css/boxicons.min.css" rel="stylesheet">
    <link href="~/assets/vendor/glightbox/css/glightbox.min.css" rel="stylesheet">
    <link href="~/assets/vendor/swiper/swiper-bundle.min.css" rel="stylesheet">

    <!-- Template Main CSS File -->
    <link href="~/assets/css/style.css" rel="stylesheet">

    <!-- =======================================================
    * Template Name: Eterna
    * Template URL: https://bootstrapmade.com/eterna-free-multipurpose-bootstrap-template/
    * Updated: Mar 17 2024 with Bootstrap v5.3.3
    * Author: BootstrapMade.com
    * License: https://bootstrapmade.com/license/
    ======================================================== -->
</head>

<body>

    <!-- ======= Header ======= -->
    <header id="header" class="d-flex align-items-center">
        <div class="container d-flex justify-content-between align-items-center">

            <div class="logo">
                <h1><a href="index.html">Eterna</a></h1>
                <!-- Uncomment below if you prefer to use an image logo -->
                <!-- <a href="index.html"><img src="~/assets/img/logo.png" alt="" class="img-fluid"></a>-->
            </div>

            <nav id="navbar" class="navbar">
                <ul>
                    <li><a asp-controller="Home" asp-action="index">Home</a></li>
                    <li><a asp-controller="About" asp-action="index">About</a></li>
                    <li><a asp-controller="Services" asp-action="index">Services</a></li>
                    <li><a asp-controller = "portfolio" asp-action="index">Portfolio</a></li>
                    <li><a asp-controller="Team" asp-action="index">Team</a></li>
                    <li><a href="pricing.html">Pricing</a></li>
                    <li><a href="blog.html">Blog</a></li>
                    <li class="dropdown">
                        <a href="#"><span>Drop Down</span> <i class="bi bi-chevron-down"></i></a>
                        <ul>
                            <li><a href="#">Drop Down 1</a></li>
                            <li class="dropdown">
                                <a href="#"><span>Deep Drop Down</span> <i class="bi bi-chevron-right"></i></a>
                                <ul>
                                    <li><a href="#">Deep Drop Down 1</a></li>
                                    <li><a href="#">Deep Drop Down 2</a></li>
                                    <li><a href="#">Deep Drop Down 3</a></li>
                                    <li><a href="#">Deep Drop Down 4</a></li>
                                    <li><a href="#">Deep Drop Down 5</a></li>
                                </ul>
                            </li>
                            <li><a href="#">Drop Down 2</a></li>
                            <li><a href="#">Drop Down 3</a></li>
                            <li><a href="#">Drop Down 4</a></li>
                        </ul>
                    </li>
                    <li><a href="contact.html">Contact</a></li>
                </ul>
                <i class="bi bi-list mobile-nav-toggle"></i>
            </nav><!-- .navbar -->

        </div>
    </header><!-- End Header -->
    @RenderBody();

    <!-- ======= Footer ======= -->
    <footer id="footer">

        <div class="footer-newsletter">
            <div class="container">
                <div class="row">
                    <div class="col-lg-6">
                        <h4>Our Newsletter</h4>
                        <p>Tamen quem nulla quae legam multos aute sint culpa legam noster magna</p>
                    </div>
                    <div class="col-lg-6">
                        <form action="" method="post">
                            <input type="email" name="email"><input type="submit" value="Subscribe">
                        </form>
                    </div>
                </div>
            </div>
        </div>

        <div class="footer-top">
            <div class="container">
                <div class="row">

                    <div class="col-lg-3 col-md-6 footer-links">
                        <h4>Useful Links</h4>
                        <ul>
                            <li><i class="bx bx-chevron-right"></i> <a href="#">Home</a></li>
                            <li><i class="bx bx-chevron-right"></i> <a href="#">About us</a></li>
                            <li><i class="bx bx-chevron-right"></i> <a href="#">Services</a></li>
                            <li><i class="bx bx-chevron-right"></i> <a href="#">Terms of service</a></li>
                            <li><i class="bx bx-chevron-right"></i> <a href="#">Privacy policy</a></li>
                        </ul>
                    </div>

                    <div class="col-lg-3 col-md-6 footer-links">
                        <h4>Our Services</h4>
                        <ul>
                            <li><i class="bx bx-chevron-right"></i> <a href="#">Web Design</a></li>
                            <li><i class="bx bx-chevron-right"></i> <a href="#">Web Development</a></li>
                            <li><i class="bx bx-chevron-right"></i> <a href="#">Product Management</a></li>
                            <li><i class="bx bx-chevron-right"></i> <a href="#">Marketing</a></li>
                            <li><i class="bx bx-chevron-right"></i> <a href="#">Graphic Design</a></li>
                        </ul>
                    </div>

                    <div class="col-lg-3 col-md-6 footer-contact">
                        <h4>Contact Us</h4>
                        <p>
                            A108 Adam Street <br>
                            New York, NY 535022<br>
                            United States <br><br>
                            <strong>Phone:</strong> +1 5589 55488 55<br>
                            <strong>Email:</strong> info@example.com<br>
                        </p>

                    </div>

                    <div class="col-lg-3 col-md-6 footer-info">
                        <h3>About Eterna</h3>
                        <p>Cras fermentum odio eu feugiat lide par naso tierra. Justo eget nada terra videa magna derita valies darta donna mare fermentum iaculis eu non diam phasellus.</p>
                        <div class="social-links mt-3">
                            <a href="#" class="twitter"><i class="bx bxl-twitter"></i></a>
                            <a href="#" class="facebook"><i class="bx bxl-facebook"></i></a>
                            <a href="#" class="instagram"><i class="bx bxl-instagram"></i></a>
                            <a href="#" class="google-plus"><i class="bx bxl-skype"></i></a>
                            <a href="#" class="linkedin"><i class="bx bxl-linkedin"></i></a>
                        </div>
                    </div>

                </div>
            </div>
        </div>

        <div class="container">
            <div class="copyright">
                &copy; Copyright <strong><span>Eterna</span></strong>. All Rights Reserved
            </div>
            <div class="credits">
                <!-- All the links in the footer should remain intact. -->
                <!-- You can delete the links only if you purchased the pro version. -->
                <!-- Licensing information: https://bootstrapmade.com/license/ -->
                <!-- Purchase the pro version with working PHP/AJAX contact form: https://bootstrapmade.com/eterna-free-multipurpose-bootstrap-template/ -->
                Designed by <a href="https://bootstrapmade.com/">BootstrapMade</a>
            </div>
        </div>
    </footer><!-- End Footer -->

    <a href="#" class="back-to-top d-flex align-items-center justify-content-center"><i class="bi bi-arrow-up-short"></i></a>

    <!-- Vendor JS Files -->
    <script src="~/assets/vendor/purecounter/purecounter_vanilla.js"></script>
    <script src="~/assets/vendor/bootstrap/js/bootstrap.bundle.min.js"></script>
    <script src="~/assets/vendor/glightbox/js/glightbox.min.js"></script>
    <script src="~/assets/vendor/isotope-layout/isotope.pkgd.min.js"></script>
    <script src="~/assets/vendor/swiper/swiper-bundle.min.js"></script>
    <script src="~/assets/vendor/waypoints/noframework.waypoints.js"></script>
    <script src="~/assets/vendor/php-email-form/validate.js"></script>

    <!-- Template Main JS File -->
    <script src="~/assets/js/main.js"></script>

</body>

</html>

MVC-Eterna/Views/Team/Index.cshtml
@model TeamViewModel
<main id="main">

    <!-- ======= Breadcrumbs ======= -->
    <section id="breadcrumbs" class="breadcrumbs">
        <div class="container">

            <ol>
                <li><a href="index.html">Home</a></li>
                <li>Team</li>
            </ol>
            <h2>Team</h2>

        </div>
    </section><!-- End Breadcrumbs -->
    <!-- ======= Team Section ======= -->
    <section id="team" class="team">
        <div class="container">

            <div class="row">
                @foreach (Member item in Model.Members)
                {
                    <div class="col-lg-4 col-md-6 d-flex align-items-stretch">
                        <div class="member">
                            <img src="assets/img/team/@item.Image" alt="">
                            <h4>@item.Name</h4>
                            <span>@item.Occupation</span>
                            <p>
                                @item.Description
                            </p>
                            <div class="social">
                               @foreach (SocialMedia sns in item.SocialMedia)
                                {
                                    <a href="@sns.Name"><i class="bi @sns.Icon"></i></a>
                                }
                            </div>
                        </div>
                    </div>
                }

            </div>

        </div>
    </section><!-- End Team Section -->

</main><!-- End #main -->